# yaml 配置
version: '3'
services:
  server:
    build: .
    container_name: server
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    network_mode: host
  postgres:
    image: postgres:12.19-alpine3.20
    environment:
      - POSTGRES_PASSWORD=muzimu2024
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"