# http设置
http:
  # 开放端口
  port: ":8080"
  url_prefix: "http://localhost:8080"
  allowed_origins:
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"
    - "http://localhost:8001"
    - "http://127.0.0.1:8001"


# 日志文件设置
logfile_setting:
  filename: "Gin-Template.log"
  maxsize: 100
  maxage: 7
  maxbackups: 7