# 运行模式 (maintain 维护中，其他没区别)
runmode: dev
# 应用设置
app:
  APPID: "08f3dc95"
  SecretKey: "94bec73836dfec04a87ad18576bb1fa2"
  Cache: true


# http设置
http:
  # 开放端口
  port: 9011
  url_prefix: "http://localhost:9011"
  allowed_origins:
    - "https://*.siruijie.com.cn"
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"
    - "http://localhost:8001"
    - "http://127.0.0.1:8001"


# 日志文件设置
logfile_enable: false
#logfile_enable: true
logfile_setting:
  filename: "./logs/log"
  maxsize: 100
  localtime: true